title: "Plozen Tech Blog"
description: "Plozen Tech Blog에서는 소프트웨어 개발과 IT 혁신을 위한 기술 지식을 공유합니다."
author: Plozen Tech Blog
github: https://github.com/moony01
about: "Plozen Tech Blog에서는 소프트웨어 개발과 IT 혁신을 위한 기술 지식을 공유합니다."
disqus_shortname: moony-1
google_analytics: G-J7NNCSLXY2
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    # - icon: fa-linkedin
    #   link: "#"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/moony01"
    - icon: fa-instagram
      link: "https://www.instagram.com/moony.1201/"

# share:
  # twitter_username: github.io
  # fb_appid: 1749788565247320

urls:
    - text: 개발자 이력서
      url: /about/
    - text: 토이 프로젝트 링크
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://moony01.com"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: ['development']
